const products = [
    { id: 1, name: "Smartphone X", category: "Eletrônicos", stock: 10, price: 999.99, image: "img/iphonex_front_back_glass_big.jpg.large.jpg" },
    { id: 2, name: "Notebook Pro", category: "Eletrônicos", stock: 5, price: 1999.99, image: "img/notebookPro.jpg" },
    { id: 3, name: "Fone de Ouvido", category: "Eletrônicos", stock: 20, price: 99.99, image: "img/fonedeouvido.jpg" },
    { id: 4, name: "Camiseta Azul", category: "Roupas", stock: 15, price: 29.99, image: "img/camisetaAzul.jpg" },
    { id: 5, name: "Calça Jeans", category: "Roupas", stock: 12, price: 59.99, image: "img/calcaJeans.jpg" },
    { id: 6, name: "Jaqueta de Couro", category: "Roupas", stock: 8, price: 129.99, image: "img/jaquetaCouro.jpg" },
    { id: 7, name: "Relógio Digital", category: "Acessórios", stock: 25, price: 49.99, image: "img/relogioDigital.jpg" },
    { id: 8, name: "Óculos de Sol", category: "Acessórios", stock: 18, price: 39.99, image: "img/oculosDeSol.jpg" },
    { id: 9, name: "Cinto de Couro", category: "Acessórios", stock: 30, price: 19.99, image: "img/cintoCouro.jpg" },
    { id: 10, name: "Smartwatch", category: "Eletrônicos", stock: 7, price: 149.99, image: "img/smartwatch.jpg" },
    { id: 11, name: "Tablet", category: "Eletrônicos", stock: 4, price: 299.99, image: "img/tablet.jpg" },
    { id: 12, name: "Camera Digital", category: "Eletrônicos", stock: 3, price: 499.99, image: "img/cameraDigital.jpg" },
    { id: 13, name: "Camisa Polo", category: "Roupas", stock: 10, price: 34.99, image: "img/camisaPolo.jpg" },
    { id: 14, name: "Shorts Esportivo", category: "Roupas", stock: 20, price: 24.99, image: "img/shortEsportivo.jpg" },
    { id: 15, name: "Vestido de Flor", category: "Roupas", stock: 6, price: 49.99, image: "img/vestidoFloral.jpg" },
    { id: 16, name: "Boné", category: "Acessórios", stock: 22, price: 14.99, image: "img/bone.jpg" },
    { id: 17, name: "Mochila", category: "Acessórios", stock: 15, price: 69.99, image: "img/mochila.jpg" },
    { id: 18, name: "Carteira", category: "Acessórios", stock: 28, price: 29.99, image: "img/carteira.jpg" },
    { id: 19, name: "Televisão 4K", category: "Eletrônicos", stock: 2, price: 799.99, image: "img/tv.jpg" },
    { id: 20, name: "Console de Jogos", category: "Eletrônicos", stock: 5, price: 399.99, image: "img/console.jpg" },
    { id: 21, name: "Mouse Sem Fio", category: "Eletrônicos", stock: 15, price: 29.99, image: "img/mouse.jpg" },
    { id: 22, name: "Camiseta Estampada", category: "Roupas", stock: 18, price: 19.99, image: "img/camisetaEstampada.jpeg" },
    { id: 23, name: "Saia", category: "Roupas", stock: 7, price: 39.99, image: "img/saia.jpg" },
    { id: 24, name: "Blusa de Lã", category: "Roupas", stock: 9, price: 59.99, image: "img/camisaLa.jpg" },
    { id: 25, name: "Pulseira", category: "Acessórios", stock: 25, price: 9.99, image: "img/pulseira.png" },
    { id: 26, name: "Colar", category: "Acessórios", stock: 20, price: 24.99, image: "img/colar.jpg" },
    { id: 27, name: "Anel", category: "Acessórios", stock: 30, price: 14.99, image: "img/anel.jpg" },
    { id: 28, name: "Carregador Portátil", category: "Eletrônicos", stock: 12, price: 19.99, image: "img/carregadorPortatil.jpg" },
    { id: 29, name: "Teclado Mecânico", category: "Eletrônicos", stock: 8, price: 89.99, image: "img/teclado.jpg" },
    { id: 30, name: "Caixa de Som Bluetooth", category: "Eletrônicos", stock: 6, price: 59.99, image: "img/caixaDeSom.jpg" },
];